build:
  environment:
    variables:
      WP_TESTS_DB_NAME: 'wp_phpunit_tests'
      WP_TESTS_DB_USER: 'root'
      WP_TESTS_DB_PASS: ''
      WP_TESTS_DB_HOST: 'localhost'
  project_setup:
    before:
      - mysql -e "CREATE DATABASE wp_phpunit_tests"
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit
            coverage:
              file: build/logs/clover.xml
              format: clover

checks:
  php:
    coding_standard:
      name: WordPress
    code_rating: true
    duplication: true

build_failure_conditions:
  - 'issues.label("bug").exists'
